name: Latest blog post workflow

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Fetch Posts from OnGTA 6
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: 4
          feed_list: "https://ongta6.com/feed/"
          comment_tag_name: "BLOG-POST-LIST"
          commit_message: "Updated README with the latest OnGTA 6 blog posts"
      
      - name: Fetch Posts from Free Games GG
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: 4
          feed_list: "https://freegamesgg.com/feed"
          comment_tag_name: "BLOG-POST-LIST2"
          commit_message: "Updated README with the latest Free Games GG blog posts"

      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git diff --staged --quiet || git commit -m "Updated README with the latest blog posts"
          git push
